FROM centos:7

RUN yum -y update && \
    yum -y upgrade

# RUN yum -y install yum-utils
#
# COPY nginx.repo /etc/yum.repos.d/nginx.repo
#
# RUN yum -y install nginx
#
# COPY mysql57-community-release-el7-10.noarch.rpm /
#
# RUN rpm -Uvh /mysql57-community-release-el7-10.noarch.rpm
#
# RUN yum install -y mysql-community-server
#
# RUN rm /mysql57-community-release-el7-10.noarch.rpm

    # yum -y install epel-release && \
    # rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && \
    # yum -y install php72w php72w-cli php72w-fpm php72w-common php72w-devel
